### ISSUE TITLE
[Todo]SQL 수정 필요

### ISSUE THREAD

**Issue by pjh612** [pjh612/FootBall_Love#55]
## 🥝 작업 내용

- [x] MemberTest의 isDuplicationId 통과 x
- [x] MemberTest의 멤버_이메일 중복확인 통과 x 
- [x] isDuplication과 멤버_이메일 중복확인 함수에서 사용하는 SQL 수정 필요.
## 🌽 작업 설명
- 해당 테스트 및 관련 함수에서 사용되는 SQL은 JPQL 문법에 맞지 않으므로 JPQL에 맞게 다시 수정을 해야합니다 (대문자 소문자 등)
- selectMemberAuthority 에서 사용하는 SQL에도 문제가 있었으나 제가 수정을 하였고 추후 pull 하겠습니다.

**Comment by SiJun-Yoo** [comment]
오늘 확인해볼게요
